name: Run Code Scanner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: self-hosted

    steps:
      - name: Checkout current repository code
        uses: actions/checkout@v3

      - name: Download code-scanner JAR
        run: |
          wget -O code-scanner.jar https://github.com/Stefan923/code-scanner/raw/master/target/code-scanner-1.0-SNAPSHOT.jar

      - name: Run code scanner on this repository
        run: |
          java -jar code-scanner.jar . benchmark
