name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "master", "test-branch" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Stage
      run: mkdir staging && cp target/*.jar staging
    - name: Run JAR files
      run: |
        for jar_file in staging/*.jar; do
          mvn exec:java -Dexec.mainClass=me.opopescu.test_octane_github_actions.Main -Dexec.args=""
        done
