# This is a basic workflow to help you get started with Actions

name: ALMOctaneGitHubActions

# Events the integration should be triggered on
on:
  # Triggers the workflow on requested, completed types
  workflow_run:
    # List of workflows to integrate with ALM Octane
    workflows: [ SCTestPoC ]
    types: [ requested, completed ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# Node configuration for allowing HTTPS requests
env:
    NODE_TLS_REJECT_UNAUTHORIZED: 0
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    octane_integration_job:
      # List of runner tags
      runs-on: [self-hosted,windows]
      name: OctaneIntegration#${{github.event.action}}#${{github.event.workflow_run.id}}
      steps:
        - name: ALM Octane GitHub Actions Integration
          # Reference to our public GitHub action
          uses: MicroFocus/alm-octane-github-actions-integration@v23.3.0
          id: gitHubActionsIntegration

          # Config parameters for the integration
          with:
            # ALM Octane connection data
            githubToken: ${{secrets.GITHUB_TOKEN}}
            unitTestResultsGlobPattern: "**/*.xml"
            octaneUrl: 'https://pmo7.almoctane.com'
            octaneSharedSpace: 2001
            octaneWorkspace: 1002
            octaneClientId: 'github_actions_n0vj9lnxdo1q6hvvlnxw6yz1e'
            octaneClientSecret: '@224822463243159243134M'
            serverBaseUrl: 'https://github.com'
