name: SpotBugs Static Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  spotbugs:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compile project
        run: |
          cd vulnerable-app
          mvn compile

      - name: Run SpotBugs
        run: |
          cd vulnerable-app
          mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs

      - name: Archive SpotBugs report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: /vulnerable-app/target/spotbugsXml.xml
