name: Semgrep Security Scan

on:
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep security audit
        run: |
          # run OWASP Top 10 Java + general security rules
          semgrep --config=p/java/owasp-top10 \
                  --config=p/security-audit \
                  --sarif-output semgrep-report.sarif \
                  vulnerable-app/src

      - name: Upload Semgrep SARIF report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif
          path: semgrep-report.sarif
